### ISSUE TITLE
How to disable the global options?

### ISSUE THREAD

**Issue by shrinidhi111** [gookit/gcli#42]

**Comment by inhere** [comment]
Is there any special scene? :)

**Comment by H-hao** [comment]
@inhere 你好，请问下 --help里面的`--ishell                  Run in an interactive shell environment(TODO)`的todo是还没完成吗？

**Comment by inhere** [comment]
是的，一个想法记录，还没实现的 ：）

**Comment by H-hao** [comment]
> 是的，一个想法记录，还没实现的 ：）

所以我也在想能不能屏蔽 global options，因为最终成品交付后发现还有个todo，有点不太合适。

**Comment by inhere** [comment]
嗯，我调整下，下个小版本发布

**Comment by H-hao** [comment]
> 嗯，我调整下，下个小版本发布

感谢。

**Comment by inhere** [comment]
hi @H-hao @shrinidhi111 

Updated on v3.0.5:

```go
	// disable global options
	gcli.GOpts().SetDisable()
```
