### ISSUE TITLE
缺少import模块

### ISSUE THREAD

**Issue by lightbrotherV** [gookit/gcli#5]
在mac平台下编译，报
github.com/gookit/gcli/v2/interact
../../pkg/mod/github.com/gookit/gcli/v2@v2.2.0/interact/read_nonwin.go:13:13: undefined: terminal
../../pkg/mod/github.com/gookit/gcli/v2@v2.2.0/interact/read_nonwin.go:13:35: undefined: syscall
异常。

**Comment by inhere** [comment]
重新发了。 你重新拉下

**Comment by inhere** [comment]
现在加了3个平台的测试了。

![image](https://user-images.githubusercontent.com/5302062/80300466-aa198280-87cf-11ea-8edb-b65733f27be8.png)
