### ISSUE TITLE
gflag.AlignLeft 赋值给 gflag.Config.Alignment 出现类型转换错误

### ISSUE THREAD

**Issue by LeonYu86** [gookit/gcli#77]
**System (please complete the following information):**

 - OS: `macOS`
 - GO Version: `1.19`

该错误出现在 github.com/gookit/gcli/v3/gflag/parser.go:52:14 及 github.com/gookit/gcli/v3/app.go:102:19 中

gflag.Config.Alignment 为 uint8 而 gflag.AlignLeft 为 PosFlag 类型.
这两处将 gflag.AlignLeft 直接赋值给了 gflag.Config.Alignment 出现了错误, 望更正

**Comment by inhere** [comment]
发了小版本修复
