### ISSUE TITLE
命令格式定义建议

### ISSUE THREAD

**Issue by JueMeiAlg** [gookit/gcli#93]
能不能支持 类似 db:seeder 这样的定义方法 可以吧一些命令 归类 显示出来好看一点

现在这样定义会 抛出异常 panic: GCli: the command name 'db:seeder' is invalid, must match: ^[a-zA-Z][\w-]*$

**Comment by inhere** [comment]
v3 改成树状结构了，可以先定义 `db` 命令，再添加子命令 `seeder`。

> v2 倒是可以使用这样的格式 `db:seeder` 定义命令名称。

**Comment by JueMeiAlg** [comment]
好
